version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: art_collection_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: art_collection
      MYSQL_USER: artuser
      MYSQL_PASSWORD: artpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - art_collection_network

  redis:
    image: redis:7-alpine
    container_name: art_collection_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - art_collection_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  art_collection_network:
    driver: bridge
